/**
 * Created by musigma on 1/3/17.
 */
export const AJAX_REQUEST = 'HOMEPAGE/AJAX_REQUEST';
export const AJAX_REQUEST_SUCCESS = 'HOMEPAGE/AJAX_REQUEST_SUCCESS';
export const AJAX_REQUEST_ERROR = 'HOMEPAGE/AJAX_REQUEST_ERROR';
export const GENERATE_FILE = 'HOMEPAGE/GENERATE_FILE';
export const GENERATE_TABLE = 'HOMEPAGE/GENERATE_TABLE';
export const GENERATE_TABLE_SUCCESS = 'HOMEPAGE/GENERATE_TABLE_SUCCESS';
export const GENERATE_SIDE_FILTER = 'HOMEPAGE/GENERATE_SIDE_FILTER';
export const GENERATE_SIDE_FILTER_SUCCESS = 'HOMEPAGE/GENERATE_SIDE_FILTER_SUCCESS';
export const FETCH_TABLE = 'HOMEPAGE/FETCH_TABLE';
export const FETCH_TABLE_SUCCESS = 'HOMEPAGE/FETCH_TABLE_SUCCESS';
export const GENERATE_URL_PARAMS = 'HOMEPAGE/GENERATE_URL_PARAMS';
export const GENERATE_URL_PARAMS_STRING = 'HOMEPAGE/GENERATE_URL_PARAMS_STRING';
export const GENERATE_TEXTBOX_QUERY_STRING = 'HOMEPAGE/GENERATE_TEXTBOX_QUERY_STRING';
export const GENERATE_SCENARIO = 'HOMEPAGE/GENERATE_SCENARIO';
export const GENERATE_NEW_SCENARIO_STRING = 'HOMEPAGE/GENERATE_NEW_SCENARIO_STRING';
export const GENERATE_NEW_SCENARIO_STORE_FORMAT = 'HOMEPAGE/GENERATE_NEW_SCENARIO_STORE_FORMAT';
export const GENERATE_NEW_SCENARIO_WEEK = 'HOMEPAGE/GENERATE_NEW_SCENARIO_WEEK';